#ifndef FM_INSTRUCTIONS_H
#define FM_INSTRUCTIONS_H

#define HALT '\x00'
#define HALT_NAME "halt"
#define LOADC '\x01'
#define LOADC_NAME "loadc"
#define ADD '\x02'
#define ADD_NAME "add"
#define SUB '\x03'
#define SUB_NAME "sub"
#define MUL '\x04'
#define MUL_NAME "mul"
#define DIV '\x05'
#define DIV_NAME "div"
#define MKBASIC '\x06'
#define MKBASIC_NAME "mkbasic"
#define GETBASIC '\x07'
#define GETBASIC_NAME "getbasic"
#define LEQ '\x08'
#define LEQ_NAME "leq"
#define NEG '\x09'
#define NEG_NAME "neg"
#define JUMP '\x0B'
#define JUMP_NAME "jump"
#define JUMPZ '\x0C'
#define JUMPZ_NAME "jumpz"
#define PUSHLOC '\x0D'
#define PUSHLOC_NAME "pushloc"
#define MKVEC '\x0E'
#define MKVEC_NAME "mkvec"
#define PUSHGLOB '\x0F'
#define PUSHGLOB_NAME "pushglob"
#define MKCLOS '\x10'
#define MKCLOS_NAME "mkclos"
#define EVAL '\x11'
#define EVAL_NAME "eval"
#define UPDATE '\x12'
#define UPDATE_NAME "update"
#define SLIDE '\x13'
#define SLIDE_NAME "slide"
#define MKFUNVAL '\x14'
#define MKFUNVAL_NAME "mkfunval"
#define TARG '\x15'
#define TARG_NAME "targ"
#define RETURN '\x16'
#define RETURN_NAME "return"
#define MARK '\x17'
#define MARK_NAME "mark"
#define APPLY '\x18'
#define APPLY_NAME "apply"
#define ALLOC '\x19'
#define ALLOC_NAME "alloc"
#define REWRITE '\x1A'
#define REWRITE_NAME "rewrite"
#define COPYGLOB '\x1B'
#define COPYGLOB_NAME "copyglob"
#define GETVEC '\x1C'
#define GETVEC_NAME "getvec"
#define NIL '\x1D'
#define NIL_NAME "nil"
#define CONS '\x1E'
#define CONS_NAME "cons"
#define TLIST '\x1F'
#define TLIST_NAME "tlist"
#define SLIDE2 '\x20'
#define SLIDE2_NAME "slide2"
#define LOADD '\x21'
#define LOADD_NAME "loadd"
#define MKSTRINGD '\x22'
#define MKSTRINGD_NAME "mkstringd"
#define FOPEN '\x23'
#define FOPEN_NAME "fopen"
#define FPUTS '\x24'
#define FPUTS_NAME "fputs"
#define FGETS '\x25'
#define FGETS_NAME "fgets"
#define APPENDS '\x26'
#define APPENDS_NAME "appends"
#define F64TOS '\x27'
#define F64TOS_NAME "f64tos"
#define F64ADD '\x28'
#define F64ADD_NAME "f64add"
#define F64SUB '\x29'
#define F64SUB_NAME "f64sub"
#define F64MUL '\x2A'
#define F64MUL_NAME "f64mul"
#define F64DIV '\x2B'
#define F64DIV_NAME "f64div"
#define ITOS '\x2C'
#define ITOS_NAME "itos"

char * fm_ins_binary_to_name(char ins);
char fm_ins_name_to_binary(char * name);
#endif
