#! /usr/bin/env bash

for test_file in ./asm/tests/*; do
  ./"$test_file"

  result=$?

  if [[ "$result" -ne 0 ]]; then
    r=$?
    echo "exiting fast on failure"
    exit $r
  fi
done

echo "success"
