#!/usr/bin/env bash

file=$(mktemp)
loadc_op=$(echo -e '\x01')
add_op=$(echo -e '\x02')
mkbasic_op=$(echo -e '\x06')
getbasic_op=$(echo -e '\x07')
jump_op=$(echo -e '\x0B')
pushloc_op=$(echo -e '\x0D')
mkvec_op=$(echo -e '\x0E')
slide_op=$(echo -e '\x13')
getvec_op=$(echo -e '\x1C')

# let (x, y) = (100, 101)
# in x + y

echo -e \
"$loadc_op"\
"\x64\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$mkbasic_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$loadc_op"\
"\x65\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$mkbasic_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$mkvec_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$getvec_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$pushloc_op"\
"\x01\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$getbasic_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$pushloc_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$getbasic_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$add_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$slide_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"\x00" > "$file"

./build/fm "$file"
result="$?"

if [[ "$result" -ne 201 ]]; then
  echo "tests/tuples failure: expected $result to equal 201"
  exit 1
fi
