#!/usr/bin/env bash

file=$(mktemp)
loadc_op=$(echo -e '\x01')
add_op=$(echo -e '\x02')
slide_op=$(echo -e '\x13')

echo -e \
"$loadc_op"\
"\x04\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$loadc_op"\
"\x01\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$loadc_op"\
"\x01\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$loadc_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$slide_op"\
"\x02\x00\x00\x00"\
"\x00\x00\x00\x00"\
"$add_op"\
"\x00\x00\x00\x00"\
"\x00\x00\x00\x00"\
"\x00" > "$file"

./build/fm "$file"
result="$?"

if [[ "$result" -ne 6 ]]; then
  echo "tests/slide failure: expected $result to equal 6"
  exit 1
fi
